"use client";

import { useMemo, useState } from "react";
import type {
  AutomatedEmailCategory,
  AutomatedEmailPreview,
} from "@/lib/automated-email-previews";

type CategoryFilter = "all" | AutomatedEmailCategory;
type PreviewDevice = "desktop" | "mobile";
type RequestStatus = "idle" | "working" | "success" | "error";

const CATEGORY_FILTERS: Array<{ id: CategoryFilter; label: string }> = [
  { id: "all", label: "All emails" },
  { id: "preorders", label: "Pre-orders" },
  { id: "customer-actions", label: "Customer actions" },
  { id: "contributors", label: "Contributors" },
];

export function AdminAutomatedEmailPreviews({
  previews,
  ownerEmail,
}: {
  previews: AutomatedEmailPreview[];
  ownerEmail: string;
}) {
  const [category, setCategory] = useState<CategoryFilter>("all");
  const [selectedId, setSelectedId] = useState(previews[0]?.id ?? "");
  const [device, setDevice] = useState<PreviewDevice>("desktop");
  const [testStatus, setTestStatus] = useState<RequestStatus>("idle");
  const [testMessage, setTestMessage] = useState("");

  const filteredPreviews = useMemo(
    () =>
      category === "all"
        ? previews
        : previews.filter((item) => item.category === category),
    [category, previews],
  );
  const selected =
    previews.find((item) => item.id === selectedId) ?? filteredPreviews[0] ?? previews[0];
  const configuredCount = previews.filter((item) => item.configured).length;

  function chooseCategory(nextCategory: CategoryFilter) {
    setCategory(nextCategory);
    const nextPreviews =
      nextCategory === "all"
        ? previews
        : previews.filter((item) => item.category === nextCategory);
    if (!nextPreviews.some((item) => item.id === selected?.id)) {
      setSelectedId(nextPreviews[0]?.id ?? "");
    }
  }

  function choosePreview(id: string) {
    setSelectedId(id);
    setTestStatus("idle");
    setTestMessage("");
  }

  async function sendTest() {
    if (!selected) return;
    setTestStatus("working");
    setTestMessage(`Sending this preview only to ${ownerEmail}…`);
    try {
      const response = await fetch("/api/admin/automated-emails/test", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ previewId: selected.id }),
      });
      const result = (await response.json()) as { error?: string; message?: string };
      if (!response.ok) {
        throw new Error(result.error ?? "The preview could not be sent.");
      }
      setTestStatus("success");
      setTestMessage(result.message ?? `Test sent only to ${ownerEmail}.`);
    } catch (error) {
      setTestStatus("error");
      setTestMessage(
        error instanceof Error ? error.message : "The preview could not be sent.",
      );
    }
  }

  if (!selected) {
    return <p className="automated-email-empty">No automated email templates are available.</p>;
  }

  return (
    <section className="automated-email-library" aria-label="Automated email previews">
      <header className="automated-email-library__header">
        <div>
          <p className="eyebrow">Template library</p>
          <h2>Every system email, in one place</h2>
          <p>These previews are generated by the same templates used for real customer and operations emails.</p>
        </div>
        <dl>
          <div><dt>Templates</dt><dd>{previews.length}</dd></div>
          <div><dt>Ready</dt><dd>{configuredCount}</dd></div>
          <div><dt>Needs setup</dt><dd>{previews.length - configuredCount}</dd></div>
        </dl>
      </header>

      <div className="automated-email-library__layout">
        <aside className="automated-email-catalog">
          <div className="automated-email-filters" role="group" aria-label="Filter automated emails">
            {CATEGORY_FILTERS.map((filter) => (
              <button
                type="button"
                className={category === filter.id ? "is-active" : undefined}
                aria-pressed={category === filter.id}
                onClick={() => chooseCategory(filter.id)}
                key={filter.id}
              >
                {filter.label}
              </button>
            ))}
          </div>

          <div className="automated-email-catalog__list">
            {filteredPreviews.map((item) => (
              <button
                type="button"
                className={selected.id === item.id ? "is-active" : undefined}
                aria-current={selected.id === item.id ? "true" : undefined}
                onClick={() => choosePreview(item.id)}
                key={item.id}
              >
                <span className={`automated-email-catalog__status ${item.configured ? "is-ready" : "is-blocked"}`} aria-hidden="true" />
                <span>
                  <small>{item.categoryLabel}</small>
                  <strong>{item.name}</strong>
                  <span>{item.trigger}</span>
                </span>
              </button>
            ))}
          </div>

          <div className="automated-email-catalog__note">
            <strong>What is not shown?</strong>
            <p>Preference changes do not currently trigger an email, so no template is presented for them yet.</p>
          </div>
        </aside>

        <article className="automated-email-detail">
          <header className="automated-email-detail__header">
            <div>
              <span>{selected.categoryLabel}</span>
              <h2>{selected.name}</h2>
              <p>{selected.description}</p>
            </div>
            <span className={`automated-email-readiness ${selected.configured ? "is-ready" : "is-blocked"}`}>
              {selected.configurationLabel}
            </span>
          </header>

          <dl className="automated-email-facts">
            <div><dt>Trigger</dt><dd>{selected.trigger}</dd></div>
            <div><dt>Audience</dt><dd>{selected.audience}</dd></div>
            <div><dt>From</dt><dd>{selected.from}</dd></div>
            <div><dt>Reply to</dt><dd>{selected.replyTo}</dd></div>
            <div><dt>Sample recipient</dt><dd>{selected.recipientExample}</dd></div>
            <div><dt>Subject</dt><dd>{selected.subject}</dd></div>
          </dl>

          <div className="automated-email-preview-toolbar">
            <div>
              <strong>Email preview</strong>
              <span>Read-only sample data</span>
            </div>
            <div role="group" aria-label="Preview width">
              <button type="button" className={device === "desktop" ? "is-active" : undefined} aria-pressed={device === "desktop"} onClick={() => setDevice("desktop")}>Desktop</button>
              <button type="button" className={device === "mobile" ? "is-active" : undefined} aria-pressed={device === "mobile"} onClick={() => setDevice("mobile")}>Mobile</button>
            </div>
          </div>

          <div className={`automated-email-preview-stage is-${device}`}>
            <div className="automated-email-preview-window">
              <div className="automated-email-preview-window__bar"><span /><span /><span /><strong>{device === "desktop" ? "Desktop inbox" : "Mobile inbox"}</strong></div>
              <iframe title={`${selected.name} email preview`} srcDoc={selected.html} sandbox="" />
            </div>
          </div>

          <section className="automated-email-links" aria-label="Links in this automated email">
            <strong>Links in this email</strong>
            {selected.links.length ? <ul>{selected.links.map((link) => <li key={link}><a href={link} target="_blank" rel="noreferrer">{link}</a></li>)}</ul> : <span>No links in this template.</span>}
          </section>

          <footer className="automated-email-test">
            <div>
              <strong>Send a safe test</strong>
              <span>The sample above will only be sent to {ownerEmail}. No customer event or delivery record is created.</span>
              {testMessage ? <p className={`is-${testStatus}`} role={testStatus === "error" ? "alert" : "status"}>{testMessage}</p> : null}
            </div>
            <button className="button button--dark" type="button" onClick={sendTest} disabled={testStatus === "working" || !selected.configured}>{testStatus === "working" ? "Sending test…" : "Send test to me"}</button>
          </footer>
        </article>
      </div>
    </section>
  );
}
