create table if not exists public.contributor_checkout_intents (
  id uuid primary key default gen_random_uuid(),
  status text not null default 'created'
    check (status in ('created', 'checkout_open', 'paid', 'expired', 'failed', 'duplicate_paid')),
  source text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  terms_version text not null,
  product_status_acknowledged_at timestamptz not null,
  marketing_opt_in boolean not null default false,
  marketing_consent_at timestamptz,
  stripe_checkout_session_id text unique,
  stripe_customer_id text,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contributors (
  id uuid primary key default gen_random_uuid(),
  checkout_intent_id uuid unique references public.contributor_checkout_intents(id) on delete set null,
  contributor_number bigint generated by default as identity unique,
  auth_user_id uuid unique references auth.users(id) on delete set null,
  email text not null,
  normalized_email text not null unique,
  full_name text not null,
  preferred_name text,
  country text,
  membership_status text not null default 'active'
    check (membership_status in ('active', 'expired', 'refunded', 'disputed')),
  founding_status boolean not null default true,
  future_discount_eligible boolean not null default true,
  paid_at timestamptz not null,
  access_starts_at timestamptz not null,
  access_expires_at timestamptz not null,
  terms_version text not null,
  terms_accepted_at timestamptz not null,
  product_status_acknowledged_at timestamptz not null,
  marketing_opt_in boolean not null default false,
  marketing_consent_at timestamptz,
  onboarding_completed_at timestamptz,
  refund_status text not null default 'none'
    check (refund_status in ('none', 'requested', 'pending', 'succeeded', 'failed')),
  welcome_email_sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.contributors
  add column if not exists checkout_intent_id uuid references public.contributor_checkout_intents(id) on delete set null;

create table if not exists public.contributor_payments (
  id uuid primary key default gen_random_uuid(),
  contributor_id uuid references public.contributors(id) on delete set null,
  checkout_intent_id uuid references public.contributor_checkout_intents(id) on delete set null,
  stripe_checkout_session_id text not null unique,
  stripe_payment_intent_id text unique,
  stripe_customer_id text,
  amount_total integer not null,
  currency text not null,
  payment_status text not null,
  paid_at timestamptz,
  refunded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.stripe_webhook_events (
  event_id text primary key,
  event_type text not null,
  status text not null default 'processing'
    check (status in ('processing', 'processed', 'failed')),
  error_message text,
  received_at timestamptz not null default now(),
  processed_at timestamptz
);

create table if not exists public.contributor_profiles (
  contributor_id uuid primary key references public.contributors(id) on delete cascade,
  preferred_name text,
  country text,
  interest_reason text,
  learning_goal text,
  uses_health_wearable boolean,
  product_areas text[] not null default '{}',
  purchase_understanding text,
  founders_wall_opt_in boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contributor_updates (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  summary text not null,
  body text not null,
  category text not null default 'Development update',
  is_published boolean not null default false,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.contributor_questions (
  id uuid primary key default gen_random_uuid(),
  contributor_id uuid not null references public.contributors(id) on delete cascade,
  question text not null check (char_length(question) between 20 and 1500),
  answer text,
  is_published boolean not null default false,
  submitted_at timestamptz not null default now(),
  answered_at timestamptz
);

create table if not exists public.contributor_events (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null,
  starts_at timestamptz not null,
  event_url text,
  recording_url text,
  is_published boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.contributor_votes (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null,
  options jsonb not null,
  closes_at timestamptz not null,
  is_published boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.contributor_vote_responses (
  vote_id uuid not null references public.contributor_votes(id) on delete cascade,
  contributor_id uuid not null references public.contributors(id) on delete cascade,
  option_id text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (vote_id, contributor_id)
);

create table if not exists public.contributor_research_opportunities (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text not null,
  eligibility text not null,
  apply_url text,
  is_published boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists contributor_checkout_intents_created_idx
  on public.contributor_checkout_intents(created_at desc);
create index if not exists contributor_payments_contributor_idx
  on public.contributor_payments(contributor_id);
create unique index if not exists contributors_checkout_intent_unique_idx
  on public.contributors(checkout_intent_id) where checkout_intent_id is not null;
create index if not exists contributor_updates_published_idx
  on public.contributor_updates(published_at desc) where is_published;
create index if not exists contributor_questions_published_idx
  on public.contributor_questions(answered_at desc) where is_published;
create index if not exists contributor_events_starts_idx
  on public.contributor_events(starts_at);

alter table public.contributor_checkout_intents enable row level security;
alter table public.contributors enable row level security;
alter table public.contributor_payments enable row level security;
alter table public.stripe_webhook_events enable row level security;
alter table public.contributor_profiles enable row level security;
alter table public.contributor_updates enable row level security;
alter table public.contributor_questions enable row level security;
alter table public.contributor_events enable row level security;
alter table public.contributor_votes enable row level security;
alter table public.contributor_vote_responses enable row level security;
alter table public.contributor_research_opportunities enable row level security;

comment on table public.contributors is
  'Paid Frame Founding Contributor memberships. Card data remains with Stripe.';
comment on column public.contributor_profiles.purchase_understanding is
  'Post-purchase comprehension response. Must not be used to collect medical information.';
