create table if not exists public.preorder_checkout_intents (
  id uuid primary key default gen_random_uuid(),
  status text not null default 'created'
    check (status in ('created', 'checkout_open', 'paid', 'expired', 'failed')),
  sku text not null,
  quantity smallint not null default 1 check (quantity between 1 and 5),
  unit_amount integer not null check (unit_amount > 0),
  currency text not null check (char_length(currency) = 3),
  estimated_delivery text not null,
  source text,
  utm_source text,
  utm_medium text,
  utm_campaign text,
  terms_version text not null,
  product_status_version text not null,
  terms_accepted_at timestamptz not null,
  product_status_acknowledged_at timestamptz not null,
  marketing_opt_in boolean not null default false,
  marketing_consent_at timestamptz,
  stripe_checkout_session_id text unique,
  stripe_customer_id text,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.preorders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  checkout_intent_id uuid not null unique references public.preorder_checkout_intents(id) on delete restrict,
  stripe_checkout_session_id text not null unique,
  stripe_customer_id text,
  email text not null,
  normalized_email text not null,
  full_name text not null,
  phone text,
  shipping_address jsonb not null,
  order_status text not null default 'placed'
    check (order_status in ('placed', 'cancelled', 'completed')),
  payment_status text not null default 'paid'
    check (payment_status in ('paid', 'refund_pending', 'refund_failed', 'partially_refunded', 'refunded', 'disputed')),
  fulfillment_status text not null default 'on_hold'
    check (fulfillment_status in ('on_hold', 'ready', 'processing', 'shipped', 'delivered', 'returned')),
  amount_subtotal integer not null check (amount_subtotal >= 0),
  amount_shipping integer not null default 0 check (amount_shipping >= 0),
  amount_tax integer not null default 0 check (amount_tax >= 0),
  amount_total integer not null check (amount_total > 0),
  amount_refunded integer not null default 0 check (amount_refunded >= 0),
  currency text not null check (char_length(currency) = 3),
  estimated_delivery text not null,
  terms_version text not null,
  product_status_version text not null,
  terms_accepted_at timestamptz not null,
  product_status_acknowledged_at timestamptz not null,
  marketing_opt_in boolean not null default false,
  marketing_consent_at timestamptz,
  placed_at timestamptz not null,
  confirmation_email_sent_at timestamptz,
  cancelled_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.preorder_order_items (
  id uuid primary key default gen_random_uuid(),
  preorder_id uuid not null references public.preorders(id) on delete cascade,
  sku text not null,
  product_name text not null,
  quantity smallint not null check (quantity > 0),
  unit_amount integer not null check (unit_amount > 0),
  currency text not null check (char_length(currency) = 3),
  created_at timestamptz not null default now(),
  unique (preorder_id, sku)
);

create table if not exists public.preorder_payments (
  id uuid primary key default gen_random_uuid(),
  preorder_id uuid not null references public.preorders(id) on delete restrict,
  checkout_intent_id uuid not null references public.preorder_checkout_intents(id) on delete restrict,
  stripe_checkout_session_id text not null unique,
  stripe_payment_intent_id text unique,
  stripe_customer_id text,
  payment_kind text not null default 'full_payment'
    check (payment_kind in ('full_payment', 'deposit', 'balance')),
  amount_total integer not null check (amount_total > 0),
  amount_refunded integer not null default 0 check (amount_refunded >= 0),
  currency text not null check (char_length(currency) = 3),
  payment_status text not null,
  paid_at timestamptz,
  refunded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.preorder_events (
  id uuid primary key default gen_random_uuid(),
  preorder_id uuid not null references public.preorders(id) on delete cascade,
  event_key text not null unique,
  event_type text not null,
  source text not null default 'system',
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.preorder_email_deliveries (
  id uuid primary key default gen_random_uuid(),
  preorder_id uuid not null references public.preorders(id) on delete cascade,
  email_type text not null,
  recipient text not null,
  delivery_key text not null unique,
  status text not null default 'pending'
    check (status in ('pending', 'sent', 'failed')),
  provider_message_id text,
  error_message text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists preorder_checkout_intents_created_idx
  on public.preorder_checkout_intents(created_at desc);
create index if not exists preorders_email_idx
  on public.preorders(normalized_email, placed_at desc);
create index if not exists preorders_status_idx
  on public.preorders(order_status, payment_status, fulfillment_status);
create index if not exists preorder_payments_preorder_idx
  on public.preorder_payments(preorder_id);
create index if not exists preorder_events_preorder_idx
  on public.preorder_events(preorder_id, created_at desc);

alter table public.preorder_checkout_intents enable row level security;
alter table public.preorders enable row level security;
alter table public.preorder_order_items enable row level security;
alter table public.preorder_payments enable row level security;
alter table public.preorder_events enable row level security;
alter table public.preorder_email_deliveries enable row level security;

comment on table public.preorders is
  'Frame physical-device pre-orders. Card data remains with Stripe.';
comment on column public.preorders.estimated_delivery is
  'Immutable delivery wording shown when the customer placed the order.';
comment on column public.preorders.shipping_address is
  'Shipping address snapshot collected by Stripe Checkout.';
